  name: nthtodolist
  description: "A new Flutter project."
  publish_to: 'none'
  version: 0.1.0

  environment:
    sdk: ^3.7.2

  dependencies:
    flutter:
      sdk: flutter
    provider: ^6.1.5
    sqflite: ^2.4.2
    flex_color_picker: ^3.7.1
    table_calendar: ^3.2.0
    path: ^1.9.1

  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^5.0.0

  flutter:
    uses-material-design: true
